#### (1)-

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
type(list_)

list

In [3]:
type(array_list)

numpy.ndarray

In [6]:
array_list.dtype

dtype('<U1')

##### the datatype of variable list_ is list. It is a list containing string elements. The datatype of variable array_list is ndarray. It is an array. The elements present inside the array are strings.

#### (2)-

In [10]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### (3)-

In [14]:
array_list = np.array(object = list_, dtype = int)

In [15]:
array_list

array([1, 2, 3, 4, 5])

##### Yes, the data type of each element present in the variables-  list_ and array_list is different.

In [16]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [17]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#### (4)-

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
num_array.shape

(2, 3)

In [23]:
num_array.size

6

#### (5)-

In [24]:
# a 3*3 matrix consisting of zeros-

arr= np.zeros((3,3))

In [25]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### (6)-

In [26]:
# an identity matrix of shape(5,5)-

arr1= np.eye(5)

In [27]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])